name: Accessibility Issue
description: Report an accessibility problem
title: "[A11y]: "
labels: ["accessibility", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping make the STACK website more accessible!
        
        We aim to meet WCAG 2.1 Level AA standards.
  
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Which page has the accessibility issue?
      placeholder: e.g., https://stack-assessment.org/GetStarted
    validations:
      required: true
  
  - type: dropdown
    id: wcag-principle
    attributes:
      label: WCAG Principle
      description: Which WCAG principle does this relate to?
      options:
        - Perceivable (can users perceive the content?)
        - Operable (can users use the interface?)
        - Understandable (can users understand the content and interface?)
        - Robust (is the content robust enough for different technologies?)
        - Not sure
    validations:
      required: true
  
  - type: textarea
    id: issue
    attributes:
      label: Accessibility Issue
      description: Describe the accessibility problem
      placeholder: The issue is...
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Who is Affected
      description: Which users are affected by this issue?
      placeholder: e.g., Screen reader users, keyboard-only users, color blind users, etc.
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this accessibility issue?
      options:
        - Critical (blocks access completely)
        - High (major barrier)
        - Medium (significant inconvenience)
        - Low (minor issue)
    validations:
      required: true
  
  - type: textarea
    id: assistive-tech
    attributes:
      label: Assistive Technology Used
      description: What assistive technology were you using when you found this issue?
      placeholder: e.g., NVDA, JAWS, VoiceOver, keyboard only, screen magnifier, etc.
  
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please share it
      placeholder: This could be fixed by...
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
